### ISSUE TITLE
Grayscale Images

### ISSUE THREAD

**Issue by ayaanzhaque** [usuyama/pytorch-unet#15]
Hi, How do I change the model to input grayscale images instead of 3 channel images?
Thanks

**Comment by usuyama** [comment]
@ayaanzhaque 

One way is to convert your grayscale images to 3 channels (just repeat 3 times).
e.g. https://stackoverflow.com/questions/50243709/how-to-convert-a-1-channel-image-into-a-3-channel-with-pil

Another way is to change the input shape of the model or add one layer to take 1 channel input.

**Comment by ayaanzhaque** [comment]
Ok thanks, I figured it out! I just changed conv1 of the Resnet to single channeled.
