### ISSUE TITLE
Dataloader Iterator Not working on custom datataset

### ISSUE THREAD

**Issue by gulzainali98** [usuyama/pytorch-unet#4]
Kindly go through this whole post
https://discuss.pytorch.org/t/dataloader-notimplemented-error/35349/2

I have described series of errors i encountered. Now Kindly let me know what is the issue with dataloader, it is returning "NotImplemented" Exception.

**Comment by usuyama** [comment]
Looks like the issue is resolved?

> So all the problems above mentioned are solved by implementing len(self) function in the dataloader.
