### ISSUE TITLE
Dimensions not working

### ISSUE THREAD

**Issue by gulzainali98** [usuyama/pytorch-unet#5]
Dimensions don't match up. 

/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py:1474: UserWarning: Using a target size (torch.Size([1966080])) that is different to the input size (torch.Size([3010560])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))

I am using BCELoss and i have tried with 192*192 dimensions as well and it is not working.

**Comment by gulzainali98** [comment]
I am using this network for binary classification

**Comment by usuyama** [comment]
Is the error from this script? https://github.com/usuyama/pytorch-unet/blob/master/pytorch_unet.py

**Comment by usuyama** [comment]
@gulzainali98 friendly ping - great if you can help me locating the issue.

**Comment by gulzainali98** [comment]
Hey sorry for late response,
This code works like a charm. It was my own mistake somewhere.

**Comment by usuyama** [comment]
Great!
