### ISSUE TITLE
Image dimensions do not match

### ISSUE THREAD

**Issue by Arktius** [usuyama/pytorch-unet#7]
I've just downloaded your jupyter notebook and got an error that the dimensions do not match. I'm talking about the very first cell in pytorch_fcn.ipynb.

Printed output: "(3,192,192,3) (3,6,192,192)"

Thanks in advance for your help. 👍

**Comment by Arktius** [comment]
Ok, I've commented out the transpose function in generate_random_data() in simulation.py. In order to see the black pixels, one has to change the calculation of input_images_rgb. Remove " * -255 +255".

**Comment by usuyama** [comment]
@Arktius Thanks for posting your solution!
